export interface PropInfo {
  type?: { name: string }
  required?: boolean
  description?: string
  defaultValue?: { value: string }
}

export interface ComponentDoc {
  description?: string
  props?: Record<string, PropInfo>
}

/**
 * Load pre-generated docgen JSON data.
 * Generated by scripts/build-docgen.mjs
 */
export async function getComponentDocs(): Promise<Record<string, ComponentDoc>> {
  try {
    const data = await import('../../static/componentData.json')
    return data.default || data
  } catch {
    return {}
  }
}

export async function getComponentDoc(componentName: string): Promise<ComponentDoc | null> {
  const docs = await getComponentDocs()
  return docs[componentName] || null
}
