/**
 * Load pre-generated example source data.
 * Generated by scripts/build-example-sources.mjs
 */
export async function getExampleSources(): Promise<Record<string, string>> {
  try {
    const data = await import('../../static/exampleSources.json')
    return data.default || data
  } catch {
    return {}
  }
}

export async function getExampleSource(examplePath: string): Promise<string | null> {
  const sources = await getExampleSources()
  return sources[examplePath] || null
}
