version: 2.1

general:
  branches:
    ignore:
      - gh-pages

orbs:
  browser-tools: circleci/browser-tools@1.4.6

docker_defaults: &docker_defaults
  docker:
    - image: cimg/node:20.18-browsers
  working_directory: ~/project/semantic-ui-react

jobs:
  bootstrap:
    <<: *docker_defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn cache
          keys:
            - v7-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v7-node-{{ .Branch }}-
            - v7-node-
      - run:
          name: Enable Corepack
          command: corepack enable
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save yarn cache
          key: v7-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  test:
    <<: *docker_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Enable Corepack
          command: corepack enable
      - run:
          name: Test JavaScript
          command: yarn test --coverage
      - run:
          name: Report coverage
          command: npx codecov --token=$CODECOV_TOKEN -f coverage/lcov.info
      - run:
          name: Test TypeScript
          command: yarn tsd:test
      - run:
          name: React Compiler check
          command: yarn eslint --no-eslintrc -c eslint.config.mjs --rule '{"react-compiler/react-compiler":"error"}' src/

  lint:
    <<: *docker_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Enable Corepack
          command: corepack enable
      - run:
          name: Lint
          command: yarn lint

  cypress:
    <<: *docker_defaults
    steps:
      - attach_workspace:
          at: ~/
      - browser-tools/install-chrome
      - run:
          name: Enable Corepack
          command: corepack enable
      - run:
          name: Build
          command: yarn build:docs
          environment:
            STAGING: true
      - run:
          name: Cypress run
          command: yarn start-server-and-test 'yarn preview --host 0.0.0.0 --port 3000' 3000 'yarn percy exec -- cypress run'

workflows:
  version: 2
  main:
    jobs:
      - bootstrap
      - test:
          requires:
            - bootstrap
      - lint:
          requires:
            - bootstrap
      - cypress:
          requires:
            - bootstrap
